# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graphyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graphyApp

  target 'graphyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'graphyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage', '~> 4.0'

end
